import { ConversionSettings } from '../types';

export const isXexFile = (data: Uint8Array): boolean => {
  if (data.length < 4) return false;
  // Check for XEX2 magic: 58 45 58 32
  return data[0] === 0x58 && data[1] === 0x45 && data[2] === 0x58 && data[3] === 0x32;
};

export const convertToCSource = (
  data: Uint8Array,
  settings: ConversionSettings
): string => {
  const { variableName, bytesPerRow, useHex, addStaticConst, includeSizeVar } = settings;
  
  const isXex = isXexFile(data);
  
  let output = `/* Generated by XEX to C Converter */\n`;
  output += `/* Source File: ${settings.variableName}.xex */\n`;
  output += `/* Format: ${isXex ? 'Xbox 360 Executable (XEX2)' : 'Binary Data'} */\n`;
  output += `/* Size: ${data.length} bytes */\n\n`;

  if (isXex) {
     output += `/* NOTE: This is a raw byte array dump of the XEX file.\n`;
     output += `   To reverse engineer logic, use the 'Decompile' mode. */\n\n`;
  }

  if (includeSizeVar) {
    output += `const unsigned int ${variableName}_len = ${data.length};\n\n`;
  }

  const qualifier = addStaticConst ? 'static const' : 'const';
  output += `${qualifier} unsigned char ${variableName}[] = {\n`;

  let row = '  ';
  for (let i = 0; i < data.length; i++) {
    const byte = data[i];
    const str = useHex 
      ? `0x${byte.toString(16).padStart(2, '0').toUpperCase()}` 
      : byte.toString();
    
    row += str;
    
    if (i < data.length - 1) {
      row += ', ';
    }

    // Check end of row
    if ((i + 1) % bytesPerRow === 0) {
      output += row + '\n';
      row = '  ';
    }
  }

  if (row.trim() !== '') {
    output += row + '\n';
  }

  output += `};\n`;

  return output;
};

export const sanitizeVariableName = (fileName: string): string => {
  return fileName
    .replace(/[^a-zA-Z0-9_]/g, '_') // Replace non-alphanumeric with _
    .replace(/^_+|_+$/g, '')        // Trim leading/trailing _
    .toLowerCase();
};

export const getHexDump = (data: Uint8Array, limit: number = 2000): string => {
  let output = '';
  const len = Math.min(data.length, limit);
  for (let i = 0; i < len; i++) {
    output += data[i].toString(16).padStart(2, '0') + ' ';
  }
  return output;
}
